name: Nuitka Build
on: [push]

jobs:
   build:
      name: Nuitka build
      strategy:
         matrix:
         os: [macos-latest, ubuntu-latest, windows-latest]
   
      runs-on: ${{ matrix.os }}
   
      steps:
         - name: Check-out repository
         uses: actions/checkout@v4
   
         - name: Setup Python
         uses: actions/setup-python@v5
         with:
            python-version: '3.12'
            cache: 'pip'
            cache-dependency-path: |
               **/requirements*.txt
   
         - name: Install your Dependencies
         run: |
            pip install -r requirements.txt -r requirements-dev.txt
   
         - name: Build Executable with Nuitka
         uses: Nuitka/Nuitka-Action@main
         with:
            nuitka-version: main
            script-name: gui.py
            # many more Nuitka options available, see action doc, but it's best
            # to use nuitka-project: options in your code, so e.g. you can make
            # a difference for macOS and create an app bundle there.
            mode: app
            enable-plugins: tk-inter
   
         - name: Upload Artifacts
         uses: actions/upload-artifact@v4
         with:
            name: ${{ runner.os }} Build
            path: | # match what's created for the 3 OSes
               build/*.exe
               build/*.bin
               build/*.app/**/*
            include-hidden-files: true

